name: metalminer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - requests=2.32.5
  - py3Dmol=2.5.3
  - streamlit=1.52.2
  - rdkit= 2025.09.2
  - pip
  - pip:
      - google-generativeai==0.8.5
# NOTE: The CCDC Python API (ccdc) must be installed separately via the CSD installer and license.
